name: exformer
channels:
  - pytorch
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - pip>=19.0.3
  - python=3.7
  - boto3
  - regex
  - numpy
  - pytorch
  - torchvision
  - cachetools
  - pip:
    - transformers>=2.8.0
    - hjson
    - fastapi[all]
    - async-lru
